### ISSUE TITLE
Rates object should also include the expiry time

### ISSUE THREAD

**Issue by libitx** [interplanaria/minercraft#1]
The full rates payload includes a `expiry_time` property, which will be important when rates are tied to fiat pricing. The simplified payload returned from `miner.fees.rates()` should also include this, so developers know how long the quote is valid for. Eg:

```js
{
  expires: "2020-04-20T16:35:03.168Z",
  mine: {data: 0.5, standard: 0.5},
  relay: {data: 0.25, standard: 0.25}
}
```

**Comment by unwriter** [comment]
Thanks for pointing it out! Just resolved with https://github.com/interplanaria/minercraft/commit/f97eac5aa79111ad1ed9830deae24abcf8ca34b1
